/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#d5fcec",
        "on-primary": "#ffffff",
        "on-background": "#002118",
        "on-tertiary-fixed": "#1c1c18",
        background: "#e6fff4",
        primary: "#006c49",
        tertiary: "#5f5e59",
        "on-primary-container": "#00422b",
        "tertiary-fixed-dim": "#c9c6c0",
        "on-surface": "#002118",
        secondary: "#2c694e",
        "surface-variant": "#c4ebdb",
        "tertiary-container": "#a5a39d",
        "inverse-primary": "#4edea3",
        error: "#ba1a1a",
        "surface-bright": "#e6fff4",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#b1f0ce",
        "on-primary-fixed-variant": "#005236",
        outline: "#6c7a71",
        "on-tertiary-container": "#3a3935",
        "on-secondary-fixed-variant": "#0e5138",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#4edea3",
        "primary-container": "#10b981",
        "surface-container": "#cff6e6",
        "outline-variant": "#bbcabf",
        "surface-container-high": "#caf1e1",
        "inverse-on-surface": "#d2f9e9",
        "secondary-fixed-dim": "#95d4b3",
        "on-secondary-fixed": "#002114",
        "surface-dim": "#bce2d3",
        "on-surface-variant": "#3c4a42",
        "on-tertiary-fixed-variant": "#474742",
        "on-secondary-container": "#316e52",
        surface: "#e6fff4",
        "primary-fixed": "#6ffbbe",
        "surface-container-highest": "#c4ebdb",
        "surface-tint": "#006c49",
        "on-primary-fixed": "#002113",
        "secondary-container": "#aeeecb",
        "tertiary-fixed": "#e5e2db",
        "inverse-surface": "#13362c",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "container-max": "1280px",
        "margin-mobile": "16px",
        unit: "8px",
        "margin-desktop": "48px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter"],
        "headline-md": ["Inter"],
        "label-md": ["Inter"],
        "headline-xl": ["Inter"],
        "body-lg": ["Inter"],
        "label-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "body-md": ["Inter"],
        headline: ["Inter"],
        display: ["Inter"],
        body: ["Inter"],
        label: ["Inter"],
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx}",
    "./src/components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
