/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#4edea3",
        "surface-variant": "#c4ebdb",
        "on-primary": "#ffffff",
        "secondary-fixed": "#b1f0ce",
        "on-background": "#002118",
        "surface-container-highest": "#c4ebdb",
        "on-primary-fixed-variant": "#005236",
        "tertiary": "#5f5e59",
        "surface-container-low": "#d5fcec",
        "inverse-primary": "#4edea3",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "inverse-on-surface": "#d2f9e9",
        "surface-container-high": "#caf1e1",
        "surface-bright": "#e6fff4",
        "error-container": "#ffdad6",
        "surface": "#e6fff4",
        "primary-container": "#10b981",
        "outline": "#6c7a71",
        "on-secondary-fixed-variant": "#0e5138",
        "tertiary-container": "#a5a39d",
        "on-tertiary-fixed": "#1c1c18",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#95d4b3",
        "error": "#ba1a1a",
        "primary": "#006c49",
        "on-primary-fixed": "#002113",
        "tertiary-fixed": "#e5e2db",
        "secondary-container": "#aeeecb",
        "outline-variant": "#bbcabf",
        "on-tertiary-container": "#3a3935",
        "secondary": "#2c694e",
        "on-tertiary-fixed-variant": "#474742",
        "on-primary-container": "#00422b",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#6ffbbe",
        "on-secondary-fixed": "#002114",
        "on-secondary-container": "#316e52",
        "on-surface": "#002118",
        "background": "#e6fff4",
        "surface-tint": "#006c49",
        "tertiary-fixed-dim": "#c9c6c0",
        "surface-dim": "#bce2d3",
        "on-surface-variant": "#3c4a42",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#13362c",
        "surface-container": "#cff6e6"
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        md: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.125rem",
        "3xl": "1.25rem",
        full: "9999px"
      },
      fontFamily: {
        sans: ["Inter", "Arial", "Helvetica", "sans-serif"],
        headline: ["Plus Jakarta Sans", "Inter", "sans-serif"],
        display: ["Plus Jakarta Sans", "Inter", "sans-serif"],
        body: ["Inter", "Arial", "Helvetica", "sans-serif"],
        label: ["Inter", "Arial", "Helvetica", "sans-serif"]
      }
    }
  },
  plugins: [],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
}
